### PR TITLE
Angle weight

### PR DESCRIPTION
**Pull request by Apostolique**
Slightly cleaner.

### CODE REVIEW

**Comment by elliots-bits** [comment]
Great I gotta admit that radians to degrees conversion was harsh.
We need to find a better implementation because right now the bot will go toward the farthest enemy, but still right toward it.
Maybe we should compute some other angles not based on the danger radius on the cells  ?

**Comment by Apostolique** [comment]
Think of different scenarios, then look for a way out. The way that my current code works is by looking for open spaces. It does that by removing all the angles that point towards an enemy. What you are left with is a range of angles where if you go towards any of them, you won't run into anyone. This stops working when there are enemies that completely surround you leaving no good angles left.

The code you are currently writing is supposed to pick up where my code falls off.

A simple idea would be to remove the furthest enemies one by one until you end up with at least one good angle. This would make the bot "tunnel vision" to deal with the closest enemies first.

**Comment by elliots-bits** [comment]
You gave me idea.

Instead of stacking the angles one by one like true or false (go / not-go), we could separate the areas in angles all having a risk/reward ratio and select the best. See what I mean  ? This would a big portion of the code but it would reproduce human behiavior much more accurately.

**Comment by Apostolique** [comment]
I think this can work. There are many ways in which something like that could get applied though.

The first step would be to rework the current food clustering algorithm to be angle based instead or area based. Then do the same for enemies.

I talked a bit about angle based clusters in: https://github.com/Apostolique/Agar.io-bot/issues/155#issuecomment-118451836

**Comment by elliots-bits** [comment]
Looking at these clusters, an angle based pathfinding would be the best approach. But sooo ressource demanding

**Pull request merged**
